services:
  coffee:
    build:
      context: .
      dockerfile: containers/app/Dockerfile.development
    command: >
      sh -c "sleep infinity"
    tty: true
    volumes:
      - node_modules:/home/node/app/node_modules
      - .:/home/node/app

volumes:
    node_modules: